### ISSUE TITLE
Cloning Issue: nnUnet Folder is Empty

### ISSUE THREAD

**Issue by shirin13** [LidiaGarrucho/MAMA-MIA#1]
Hi,

I encountered an issue when trying to clone the repository. About two weeks ago, I was able to clone the [MAMA-MIA](https://github.com/LidiaGarrucho/MAMA-MIA) repo without any problems. However, now when I attempt to clone it, I only get an empty folder for nnUnet.

Thank you!

**Comment by LidiaGarrucho** [comment]
The nnUNet is a forked repository to track the nnUNet version used to train the baseline segmentation model.
The dataset and model weights are hosted in Synapse. We have just updated the respository with source code a Jupyter notebooks to demostrate how to read and parse the clinical data, open and display the images using Python and apply common preprocessing steps.
